# Create first site
createSite:
  enabled: true
  siteName: "dg.example.org"
  dbRootUser: "root"
  adminPassword: "admin"
  installApps: "erpnext"
  dropSiteOnUninstall: false

# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: dg.example.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: auth-server-tls
  #    hosts:
  #      - auth-server.local

migrateJob:
  # Set this to true to run migrate as part of helm install/upgrade
  enable: false
  backup: true

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  fsGroupChangePolicy: "OnRootMismatch"
